"""Modelos para chatbot inteligente: for Rene Vasquez

Revision ID: 3b5222756116
Revises: 5816b1cda7c9
Create Date: 2026-03-13 16:39:26.997160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5222756116'
down_revision = '5816b1cda7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas_inteligentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patron', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('consulta_sql', sa.Text(), nullable=False),
    sa.Column('tipo_resultado', sa.String(length=50), nullable=True),
    sa.Column('ejemplo_pregunta', sa.String(length=255), nullable=True),
    sa.Column('veces_usada', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas_frecuentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(190), nullable=False),  
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(50)),
    sa.Column('palabras_clave', sa.String(255)),
    sa.Column('veces_usada', sa.Integer()),
    sa.Column('activo', sa.Boolean()),
    sa.Column('fecha_creacion', sa.DateTime()),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pregunta')
    )
    op.create_table('conversaciones_chatbot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('satisfaccion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_interacciones_chatbot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_conversacion', sa.Integer(), nullable=True),
    sa.Column('tipo_accion', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('datos_consulta', sa.JSON(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_conversacion'], ['conversaciones_chatbot.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_chatbot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_conversacion', sa.Integer(), nullable=False),
    sa.Column('es_usuario', sa.Boolean(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo_mensaje', sa.String(length=50), nullable=True),
    sa.Column('intencion_detectada', sa.String(length=100), nullable=True),
    sa.Column('entidades_extraidas', sa.JSON(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tiempo_respuesta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_conversacion'], ['conversaciones_chatbot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recomendaciones_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('tipo_recomendacion', sa.String(length=50), nullable=True),
    sa.Column('puntuacion', sa.Float(), nullable=True),
    sa.Column('razon', sa.String(length=255), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id'])
        batch_op.create_foreign_key(None, 'pedidos', ['id_pedido'], ['id'])

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['id_usuario'], ['id'])

    with op.batch_alter_table('producto_etiqueta', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'etiquetas', ['etiqueta_id'], ['id'])
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('producto_etiqueta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('recomendaciones_producto')
    op.drop_table('mensajes_chatbot')
    op.drop_table('log_interacciones_chatbot')
    op.drop_table('conversaciones_chatbot')
    op.drop_table('preguntas_frecuentes')
    op.drop_table('consultas_inteligentes')
    # ### end Alembic commands ###
