"""Migracion actualizada completa

Revision ID: 5816b1cda7c9
Revises: 86b056abdbc2
Create Date: 2026-03-10 20:51:34.488901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5816b1cda7c9'
down_revision = '86b056abdbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'pedidos', ['id_pedido'], ['id'])
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id'])

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['id_usuario'], ['id'])

    with op.batch_alter_table('producto_etiqueta', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'etiquetas', ['etiqueta_id'], ['id'])
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categorias', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('producto_etiqueta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('detalles_pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
